config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  default_url_options host: ENV['DEFAULT_URL_OPTIONS']

  root 'profile#show'
  get '/:locale' => 'schedules#index'

  scope '(:locale)', locale: /en|ru/ do
    devise_for :users
    get 'profile' => 'profile#show'

    resources :schedules, only: %i[index show new create edit update destroy] do
      resources :occupations, only: %i[index show new create edit update destroy] do
        resources :tasks, only: %i[index create update destroy]
      end

      resources :subjects, only: %i[index create update destroy]
      resources :places, only: %i[index create update destroy]
      resources :field_of_activities, only: %i[index create update destroy]
    end

    resources :habits, only: %i[index create update destroy] do
      collection do
        get 'progress'
      end
    end
    resources :habit_days, only: %i[create update destroy]

    resources :checktasks, only: %i[index create update destroy] do
      member do
        get 'done'
      end
    end

    defaults format: :json do
      namespace :api do
        namespace :v1 do
          resources :schedules, only: %i[index]
        end
      end
    end
  end
end

app/models/occupation.rb
# frozen_string_literal: true

class Occupation < ApplicationRecord
  belongs_to :schedule
  belongs_to :subject, optional: true
  belongs_to :place, optional: true
  belongs_to :field_of_activity, optional: true
  has_one_attached :appendix
  has_many :tasks

  enum week: {
    monday: 1,
    tuesday: 2,
    wednesday: 3,
    thursday: 4,
    friday: 5,
    saturday: 6,
    sunday: 7
  }

  enum type_of_week: {
    simple: 0,
    odd: 1,
    even: 2
  }

  validates_presence_of :start_date, :start_time, :end_time

  def self.custom_type_of_week
    [
      OpenStruct.new(id: :simple, title: I18n.t('.occupation.type_of_week.simple')),
      OpenStruct.new(id: :odd, title: I18n.t('.occupation.type_of_week.odd')),
      OpenStruct.new(id: :even, title: I18n.t('.occupation.type_of_week.even'))
    ]
  end

  def self.custom_week_days
    [
      OpenStruct.new(id: :monday, title: I18n.t('.occupation.week_days.mon')),
      OpenStruct.new(id: :tuesday, title: I18n.t('.occupation.week_days.tue')),
      OpenStruct.new(id: :wednesday, title: I18n.t('.occupation.week_days.wed')),
      OpenStruct.new(id: :thursday, title: I18n.t('.occupation.week_days.thu')),
      OpenStruct.new(id: :friday, title: I18n.t('.occupation.week_days.fri')),
      OpenStruct.new(id: :saturday, title: I18n.t('.occupation.week_days.sat')),
      OpenStruct.new(id: :sunday, title: I18n.t('.occupation.week_days.sun'))
    ]
  end

  def custom_week
    {
      monday: I18n.t('.occupation.week_days.mon'),
      tuesday: I18n.t('.occupation.week_days.tue'),
      wednesday: I18n.t('.occupation.week_days.wed'),
      thursday: I18n.t('.occupation.week_days.thu'),
      friday: I18n.t('.occupation.week_days.fri'),
      saturday: I18n.t('.occupation.week_days.sat'),
      sunday: I18n.t('.occupation.week_days.sun')
    }[week.to_sym]
  end

  def all_week
    @all_week ||= schedule.start_week.all_week.to_a
  end

  def current_week_day
    all_week[Occupation.weeks[week] - 1]
  end

  def color
    {
      'monday' => '#50c7c7',
      'tuesday' => '#50c75f',
      'wednesday' => '#c76b50',
      'thursday' => '#6550c7',
      'friday' => '#c75052',
      'saturday' => '#ebdd60',
      'sunday' => '#eb60bc'
    }.fetch(week, '#50c7c7')
  end
end

app/controllers/occupations_controller.rb
# frozen_string_literal: true

class OccupationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_schedule_with_prefix
  before_action :find_occupation, only: %i[edit update destroy]

  def index
    @occupations = @schedule.occupations.order(week: :asc, start_time: :asc)
  end

  def new
    @occupation = @schedule.occupations.new
  end

  def create
    @occupation = @schedule.occupations.new(create_params)

    if @occupation.save
      redirect_to @schedule, success: t('.flash.success')
    else
      flash[:danger] = t('.flash.danger')
      render :new
    end
  end

  def edit
    @places = []
    @field_of_activities = []
    @subjects = []

    if @occupation.place.present?
      @places << Place.new(
        title: t('occupations.new.form.place.prompt')
      )
    else
      @occupation.place_id = nil
    end

    if @occupation.field_of_activity.present?
      @field_of_activities << FieldOfActivity.new(
        title: t('occupations.new.form.field_of_activity.prompt')
      )
    else
      @occupation.field_of_activity_id = nil
    end

    if @occupation.subject.present?
      @subjects << Subject.new(
        title: t('occupations.new.form.subject.prompt')
      )
    else
      @occupation.subject_id = nil
    end

    @places += @schedule.places
    @field_of_activities += @schedule.field_of_activities
    @subjects += @schedule.subjects
  end

  def update
    @occupation.assign_attributes(update_params)

    if @occupation.save
      redirect_to schedule_occupations_path(@schedule), primary: t('.flash.success')
    else
      flash[:danger] = t('.flash.danger')
      render :edit
    end
  end

  def destroy
    if @occupation.destroy
      redirect_to schedule_occupations_path(@schedule)
    else
      flash[:danger] = t('.flash.danger')
    end
  end

  private

  def occupation_params
    params.require(:occupation).permit(
      :subject_id,
      :schedule_id,
      :start_date,
      :start_time,
      :end_date,
      :end_time,
      :place_id,
      :field_of_activity_id,
      :type_of_week,
      :week,
      :appendix
    )
  end

  def create_params
    occupation_params
  end

  def update_params
    occupation_params
  end
end

app/views/occupations/_form.html.erb
<div class="form-row">
  <div class='form-group col-md'>
    <%= f.label t('occupations.new.form.subject.title'), for: :subject_id  %>
      <%= f.collection_select :subject_id, (@subjects || @schedule.subjects),
                              :id, :title,
                              { prompt: t('occupations.new.form.subject.prompt') },
                              class: 'custom-select' %>
  </div>
</div>

<div class="form-row">
  <div class='form-group col-md-6'>
    <%= f.label t('occupations.new.form.week_day.title'),
                for: :week  %>
    <%= f.collection_select :week, Occupation.custom_week_days,
                      :id, :title, {}, class: 'custom-select' %>
  </div>

  <div class='form-group col-md-6'>
    <%= f.label t('occupations.new.form.type_of_week.title'),
                for: :type_of_week  %>
    <%= f.collection_select :type_of_week, Occupation.custom_type_of_week,
                      :id, :title, {}, class: 'custom-select' %>
  </div>
</div>

<div class="form-row">
  <div class='form-group col-md-6'>
    <%= f.label t('occupations.new.form.start_date.title'), for: :start_date  %>
    <%= f.date_field :start_date, type: :date, class: 'form-control', required: true %>
    <small id="start_date" class="form-text text-muted">
      <%= t('occupations.new.form.start_date.text_muted') %>
    </small>
  </div>

  <div class='form-group col-md-6'>
    <%= f.label t('occupations.new.form.end_date.title'), for: :end_date  %>
    <%= f.date_field :end_date, type: :date, class: 'form-control' %>
    <small id='end_date' class="form-text text-muted">
      <%= t('occupations.new.form.end_date.text_muted') %>
    </small>
  </div>
</div>

<div class="form-row">
  <div class='form-group col-md-6'>
    <%= f.label t('occupations.new.form.start_time.title'), for: :start_time  %>
    <%= f.time_field :start_time, type: :time, class: 'form-control', required: true %>
  </div>

  <div class='form-group col-md-6'>
    <%= f.label t('occupations.new.form.end_time.title'), for: :end_time  %>
    <%= f.time_field :end_time, type: :time, class: 'form-control', required: true %>
  </div>
</div>

<div class="form-row">
  <div class='form-group col-md-6'>
    <%= f.label t('occupations.new.form.field_of_activity.title'),
        for: :field_of_activity_id  %>
    <%= f.collection_select :field_of_activity_id,
                (@field_of_activities || @schedule.field_of_activities),
                :id, :title,
                { prompt: t('occupations.new.form.field_of_activity.prompt') },
                class: 'custom-select' %>
  </div>


  <div class='form-group col-md-6'>
    <%= f.label t('occupations.new.form.place.title'), for: :place_id  %>
    <%= f.collection_select :place_id,
                            (@places || @schedule.places),
                            :id, :title,
                            { prompt: t('occupations.new.form.place.prompt') },
                            class: 'custom-select' %>
  </div>
</div>

<div class='custom-file mb-3'>
  <%= f.file_field :appendix,
                    type: 'file',
                    class: 'custom-file-input'
  %>

  <%= f.label t('occupations.new.form.appendix.title'),
              for: :appendix,
              class: 'custom-file-label',
              'data-browse': t('occupations.new.form.appendix.data_browse')
  %>
</div>

app/views/occupations/edit.html.erb
<div class="jumbotron p-3 jumbotron-fluid bg-light">
  <h2 class="display-5"><%= t('occupations.edit.title')%></h2>
  <hr class="my-4">

  <%= link_to t('occupations.show.link.schedules.show'), schedule_path(@schedule), type: "button", class: "btn btn-outline-secondary" %>
  <%= link_to schedule_occupations_path(@schedule), type: "button", class: "btn btn-outline-secondary" do %>
     <%= t('schedules.show.link.occupations.manage') %> <span class="badge badge-light border">
     <%= @schedule.occupations.count %>
     </span>
  <% end %>

    <%= link_to schedule_subjects_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" do %>
     <%= t('schedules.show.link.subjects.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.subjects.count %>
     </span>
  <% end %>

  <%= link_to schedule_places_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" do %>
     <%= t('schedules.show.link.places.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.places.count %>
     </span>
  <% end %>

  <%= link_to schedule_field_of_activities_path(@schedule),
              type: "button",
              class: "btn btn-outline-secondary mr-1" do %>
     <%= t('schedules.show.link.field_of_activities.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.field_of_activities.count %>
     </span>
  <% end %>

  <hr class="my-4">
  <%= form_for [@schedule, @occupation], method: :put  do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit t('occupations.edit.form.submit.title'), type: 'submit', class: 'btn btn-outline-primary' %>
  <% end %>
</div>

app/views/occupations/index.html.erb
<div class="jumbotron p-3 jumbotron-fluid bg-light">
  <h2 class="display-5"><%= @schedule.title %> | <%= t('schedules.show.link.occupations.manage') %></h2>
  <hr class="my-4">
    <%= link_to t('occupations.show.link.schedules.show'), schedule_path(@schedule), type: "button", class: "btn btn-outline-secondary" %>
    <%= link_to t('schedules.show.link.occupations.new'), new_schedule_occupation_path(@schedule), type: "button", class: "btn btn-outline-success" %>
  <hr class="my-4">

  <div class="list-group">
  <% @occupations.each do |occupation| %>
  <div class='list-group-item bg-light'>
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"><%= truncate(occupation.subject&.title, length: 20) %></h5>
      <big>
        <%= link_to edit_schedule_occupation_path(@schedule, occupation), class: "btn btn btn-outline-primary" do %>
          <%= render 'icons/pencil' %>
        <% end %>
        <%= link_to [@schedule, occupation], method: :delete, data: {confirm: t('.you_sure')}, class: "btn btn btn-outline-danger" do %>
          <%= render 'icons/trash_fill' %>
        <% end %>
      </big>
    </div>
    <p class="mb-1"></p>
    <big>
      <span class="badge badge-success">
        <%= render 'icons/stopwatch' %>
        <%= occupation.start_time&.to_s(:time) %> —
        <%= occupation.end_time&.to_s(:time) %>
      </span>
      <span class="badge badge-info">
        <%= render 'icons/calendar' %>
        <%= occupation.start_date&.to_s(:date) %> —
        <%= (occupation.end_date || occupation.start_date)&.to_s(:date) %>
      </span>
    </big>
  </div>
  <% end %>
  </div>
</div>

app/views/occupations/new.html.erb
<div class="jumbotron p-3 jumbotron-fluid bg-light">
  <h2 class="display-5"><%= t('occupations.new.title')%></h2>
  <hr class="my-4">

  <%= link_to t('occupations.show.link.schedules.show'), schedule_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" %>
  <%= link_to schedule_occupations_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" do %>
     <%= t('schedules.show.link.occupations.manage') %> <span class="badge badge-light border">
     <%= @schedule.occupations.count %>
     </span>
  <% end %>

  <%= link_to schedule_subjects_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" do %>
     <%= t('schedules.show.link.subjects.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.subjects.count %>
     </span>
  <% end %>

  <%= link_to schedule_places_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" do %>
     <%= t('schedules.show.link.places.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.places.count %>
     </span>
  <% end %>

  <%= link_to schedule_field_of_activities_path(@schedule),
              type: "button",
              class: "btn btn-outline-secondary mr-1" do %>
     <%= t('schedules.show.link.field_of_activities.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.field_of_activities.count %>
     </span>
  <% end %>

  <hr class="my-4">
  <%= form_for [@schedule, @occupation] do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit t('occupations.new.form.submit.title'), type: 'submit', class: 'btn btn-outline-success' %>
  <% end %>
</div>