config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  default_url_options host: ENV['DEFAULT_URL_OPTIONS']

  root 'profile#show'
  get '/:locale' => 'schedules#index'

  scope '(:locale)', locale: /en|ru/ do
    devise_for :users
    get 'profile' => 'profile#show'

    resources :schedules, only: %i[index show new create edit update destroy] do
      resources :occupations, only: %i[index show new create edit update destroy] do
        resources :tasks, only: %i[index create update destroy]
      end

      resources :subjects, only: %i[index create update destroy]
      resources :places, only: %i[index create update destroy]
      resources :field_of_activities, only: %i[index create update destroy]
    end

    resources :habits, only: %i[index create update destroy] do
      collection do
        get 'progress'
      end
    end
    resources :habit_days, only: %i[create update destroy]

    resources :checktasks, only: %i[index create update destroy] do
      member do
        get 'done'
      end
    end

    defaults format: :json do
      namespace :api do
        namespace :v1 do
          resources :schedules, only: %i[index]
        end
      end
    end
  end
end

app/models/schedule.rb
# frozen_string_literal: true

# Schedule
class Schedule < ApplicationRecord
  has_many :occupations
  has_many :subjects
  has_many :places
  has_many :field_of_activities

  has_many :users_schedules
  has_many :users, through: :users_schedules

  validates_presence_of :title

  def start_week
    Date.today.monday
  end

  def end_week
    Date.today.sunday
  end

  def type_of_week
    current_date = Date.today
    number = current_date.strftime('%U').to_i + 1
    # If current date < start date => use only current date
    if start_date.present? && current_date >= start_date
      number = ((current_date - start_date).to_i / 7) + 1
    end

    number.odd? ? :odd : :even
  end

  def types_week
    [:simple, type_of_week]
  end

  def last_occupation_updated_at
    occupation = occupations.order(updated_at: :desc).first
    occupation&.updated_at || updated_at
  end

  def occupations_between(need_occupations, start_date, end_date)
    need_occupations.where(
      "
        (start_date >= :start_date AND start_date <= :end_date) OR
        (
          end_date IS NOT NULL AND
          start_date < :start_date AND
          end_date >= :start_date
        )
      ",
      start_date: start_date,
      end_date: end_date
    )
  end

  def occupations_this_week(need_occupations)
    occupations_between(need_occupations, start_week, end_week).order(
      week: :asc,
      start_time: :asc
    )
  end
end

app/controllers/api/v1/schedules_controller.rb
# frozen_string_literal: true

module API
  module V1
    class SchedulesController < BaseController
      def index
        @schedules = SchedulesQuery.call(current_user)
      end
    end
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_schedule, only: %i[show edit update destroy]

  def index; end

  def show
    @occupations_this_week = occupations_this_week_service.call(params)
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(create_params)

    if @schedule.save
      current_user.schedules << @schedule
      redirect_to edit_schedule_path(@schedule), success: t('.flash.success')
    else
      flash[:danger] = t('.flash.danger')
      render :new
    end
  end

  def edit; end

  def update
    @schedule.assign_attributes(update_params)

    if @schedule.save
      redirect_to edit_schedule_path(@schedule), primary: t('.flash.success')
    else
      flash[:danger] = t('.flash.danger')
      render :edit
    end
  end

  def destroy
    if @schedule.users.includes(current_user) && @schedule.destroy
      redirect_to root_path, success: t('.flash.success')
    else
      redirect_to edit_schedule_path(@schedule), danger: t('.flash.danger')
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(
      :title,
      :description,
      :start_date
    )
  end

  def create_params
    schedule_params
  end

  def update_params
    schedule_params
  end

  def occupations_this_week_service
    Occupations::ThisWeekService.new(@schedule)
  end
end

app/views/schedules/_form.html.erb
<div class="form-row">
  <div class='form-group col-md-6'>
    <%= f.label t('schedules.edit.form.title.title'), for: :title  %>
    <%= f.text_field :title,
                    class: 'form-control',
                    placeholder: t('schedules.edit.form.title.placeholder'),
                    required: true
    %>
  </div>

  <div class='form-group col-md-6'>
    <%= f.label t('schedules.edit.form.start_date.title'), for: :start_date  %>
    <%= f.date_field :start_date, type: :date, class: 'form-control' %>
    <small id="start_date" class="form-text text-muted">
      <%= t('schedules.edit.form.start_date.text_muted') %>
    </small>
  </div>
</div>

<div class="form-row">
  <div class='form-group col-md-12'>
    <%= f.label t('schedules.edit.form.description.title'), for: :description %>
    <%= f.text_area :description,
                  class: 'form-control',
                  placeholder: t('schedules.edit.form.description.placeholder'),
                  required: true
    %>
  </div>
  
</div>

app/views/schedules/edit.html.erb
<div class="jumbotron p-3 jumbotron-fluid bg-light">
  <h2 class="display-5">
    <%= @schedule.title %> | <%= t('schedules.edit.title') %>
  </h2>
  <p class="lead">
    <span class="badge badge-dark">
      <%= render 'icons/calendar' %>
      <%= @schedule.start_week %> — <%= @schedule.end_week %>
    </span>

    <span class="badge badge-dark">
      <%= t("type_of_week.#{@schedule.type_of_week.to_s}") %>
    </span>
  </p>
  <hr class="my-4">

  <%= form_for @schedule do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit t('schedules.edit.form.submit.title'), type: 'submit', class: 'btn btn-outline-primary' %>
    <%= link_to t('schedules.destroy.title'),
                schedule_path(@schedule),
                method: :delete,
                class: 'btn btn-outline-danger',
                data: { confirm: t('schedules.destroy.confirm') } %>
  <% end %>
</div>

app/views/schedules/index.html.erb
<div id="index"></div>
<%= javascript_pack_tag 'schedules/index/index', 'data-turbolinks-track': 'reload' %>

app/views/schedules/new.html.erb
<div class="jumbotron p-3 jumbotron-fluid bg-light">
  <h2 class="display-5">
    <%= t('schedules.new.title') %>
  </h2>
  <p class="lead">
    <span class="badge badge-dark">
      <%= render 'icons/calendar' %>
      <%= @schedule.start_week %> — <%= @schedule.end_week %>
    </span>

    <span class="badge badge-dark">
      <%= t("type_of_week.#{@schedule.type_of_week.to_s}") %>
    </span>
  </p>
  <hr class="my-4">

  <%= form_for @schedule do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit t('schedules.new.form.submit.title'), type: 'submit', class: 'btn btn-outline-primary' %>
  <% end %>
</div>

app/views/schedules/show.html.erb
<div class="jumbotron p-3 jumbotron-fluid bg-light">
  <h2 class="display-5"><%= @schedule.title %></h2>
  <p class="lead">
    <span class="badge badge-dark">
      <%= render 'icons/calendar' %>
      <%= @schedule.start_week %> — <%= @schedule.end_week %>
    </span>

    <span class="badge badge-dark">
      <%= t("type_of_week.#{@schedule.type_of_week.to_s}") %>
    </span>
  </p>
  <hr class="my-4">

    <%= link_to t('schedules.show.link.occupations.new'), new_schedule_occupation_path(@schedule), type: "button", class: "btn btn-outline-success m-1" %>
    <%= link_to schedule_occupations_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" do %>
     <%= t('schedules.show.link.occupations.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.occupations.count %>
     </span>
    <% end %>

    <%= link_to schedule_subjects_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" do %>
     <%= t('schedules.show.link.subjects.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.subjects.count %>
     </span>
    <% end %>

    <%= link_to schedule_places_path(@schedule), type: "button", class: "btn btn-outline-secondary m-1" do %>
     <%= t('schedules.show.link.places.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.places.count %>
     </span>
    <% end %>

    <%= link_to schedule_field_of_activities_path(@schedule),
                type: "button",
                class: "btn btn-outline-secondary mr-1" do %>
     <%= t('schedules.show.link.field_of_activities.manage') %>
     <span class="badge badge-light border">
     <%= @schedule.field_of_activities.count %>
     </span>
    <% end %>

    <%= link_to schedule_path(@schedule),
                type: "button",
                class: "btn btn-outline-secondary m-1" do %>
      <%= render 'icons/arrow_repeat' %>
    <% end %>
  <hr class="my-4">

  <div class="list-group">
    <% @occupations_this_week.each do |occupation| %>
      <% if @week.nil? || @week != occupation.week %>

        <div class="list-group-item text-light pb-0 pl-0 border-0 bg-light">
          <div class="d-flex w-100 justify-content-between">
            <h6 class='rounded p-1 mb-0' style='background: <%= occupation.color %>'>
              <small><strong><%= occupation.custom_week %></strong> |
              <%= occupation.current_week_day.to_s(:date) %>
            </small></h6>
          </div>
        </div>

        <% @week = occupation.week  %>
      <% end %>

      <div class="list-group-item rounded border bg-light">
        <div class="d-flex w-100 justify-content-between">
          <h6 class="mb-1"><strong><%= occupation.subject&.title %></strong></h6>
          <span>
            <% if occupation.field_of_activity.present? %>
              <%= link_to schedule_path(
                @schedule, field_of_activity_id: occupation.field_of_activity.id
              ), style: 'text-decoration: none' do %>
              <span class="badge btn btn-outline-secondary">
                <%= render 'icons/list_ul' %>
                <%= occupation.field_of_activity.title.downcase %>
              </span>
              <% end %>
            <% end %>

            <% if occupation.place.present? %>
              <%= link_to schedule_path(@schedule, place_id: occupation.place.id),style: 'text-decoration: none' do %>
              <span class="badge btn btn-outline-secondary">
                <%= render 'icons/geo_alt' %>
                <%= occupation.place.title.downcase %>
              </span>
              <% end %>
            <% end %>
          </span>
        </div>
        <span>

            <span class="badge btn btn-outline-secondary">
              <%= render 'icons/stopwatch' %>
              <time><%= occupation.start_time.to_s(:time) %></time> -
              <time><%= occupation.end_time.to_s(:time) %></time>
            </span>

            <%= link_to schedule_occupation_tasks_path(@schedule, occupation),
                        style: 'text-decoration: none' do %>
              <span class="badge btn btn-outline-secondary">
                <%= render 'icons/list_ul' %> <%= occupation.tasks.count %>
              </span>
            <% end %>

          <% if occupation.appendix.present? %>
            <%= link_to url_for(occupation.appendix),
              style: 'text-decoration: none',
              target: '_blank' do %>
              <span class="badge btn btn-outline-secondary">
                <%= render 'icons/paperclip' %>
              </span>
            <% end %>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>
</div>